egitimsitesi/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using egitimsitesi.Models;

namespace egitimsitesi.Controllers
{
    public class KullaniciController : Controller
    {
        private egtmSitesiEntities1 db = new egtmSitesiEntities1();

        // GET: Kullanici
        [Authorize(Roles ="Admin")]
        public ActionResult Index()
        {
            var kullanici = db.Kullanici.Include(k => k.Kodlama);
            return View(kullanici.ToList());
        }

        public ActionResult C()
        {
            ViewBag.c = db.Kodlama.Where(s => s.KodlamaID == 1).Select(s => s.StringArea).Single();
            return View();
        }
        public ActionResult Cplusplus()
        {
            ViewBag.cpp = db.Kodlama.Where(s => s.KodlamaID == 2).Select(s => s.StringArea).Single();
            return View();
        }
        public ActionResult Csharp()
        {
            ViewBag.csharp = db.Kodlama.Where(s => s.KodlamaID == 3).Select(s => s.StringArea).Single();
            return View();
        }
        public ActionResult Java()
        {
            ViewBag.java = db.Kodlama.Where(s => s.KodlamaID == 4).Select(s => s.StringArea).Single();
            return View();
        }
        // GET: Kullanici/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanici kullanici = db.Kullanici.Find(id);
            if (kullanici == null)
            {
                return HttpNotFound();
            }
            return View(kullanici);
        }

        // GET: Kullanici/Create
        public ActionResult Create()
        {
            ViewBag.KodlamaId = new SelectList(db.Kodlama, "KodlamaID", "StringArea");
            return View();
        }

        // POST: Kullanici/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "KullaniciID,isimvesoy,il,telefonNumarasi,dgmTarihi,eposta,Role,KodlamaId,hatirla,parola")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                db.Kullanici.Add(kullanici);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            ViewBag.KodlamaId = new SelectList(db.Kodlama, "KodlamaID", "StringArea", kullanici.KodlamaId);
            return View(kullanici);
        }

        // GET: Kullanici/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanici kullanici = db.Kullanici.Find(id);
            if (kullanici == null)
            {
                return HttpNotFound();
            }
            ViewBag.KodlamaId = new SelectList(db.Kodlama, "KodlamaID", "StringArea", kullanici.KodlamaId);
            return View(kullanici);
        }

        // POST: Kullanici/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "KullaniciID,isimvesoy,il,telefonNumarasi,dgmTarihi,eposta,Role,KodlamaId,hatirla,parola")] Kullanici kullanici)
        {
            if (ModelState.IsValid)
            {
                db.Entry(kullanici).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.KodlamaId = new SelectList(db.Kodlama, "KodlamaID", "StringArea", kullanici.KodlamaId);
            return View(kullanici);
        }

        // GET: Kullanici/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Kullanici kullanici = db.Kullanici.Find(id);
            if (kullanici == null)
            {
                return HttpNotFound();
            }
            return View(kullanici);
        }

        // POST: Kullanici/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Kullanici kullanici = db.Kullanici.Find(id);
            db.Kullanici.Remove(kullanici);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

egitimsitesi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script type="text/javascript" src="@Url.Content("~/Scripts/Menu.js")"></script>
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <style>
        .mySlides {
            display: none;
        }
    </style>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span style="font-size:30px;cursor:pointer" class="navbar-brand" id="menu-toggle" onclick="openNav()">Menü</span>

                <img src="~/fonts/kodkurdu.gif" width="100" height="50" />

            </div>
            <div class="navbar-collapse collapse col-md-3">

                <marquee width="32%" bgcolor="#ffffff" direction="right" scrollamount="4">
                    <font color="#ff0000" size="6">Hoş Geldiniz</font>
                </marquee>
                <div class="nav navbar-nav navbar-right col-sm-4">
                    <div class="nav navbar-nav">

                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                DIL<span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                <li> @Html.ActionLink("TR", "DilBilgisi", "Home", new { dil = "tr", sayfa = this.Request.RawUrl }, null)</li>
                                <li> @Html.ActionLink("EN", "DilBilgisi", "Home", new { dil = "en", sayfa = this.Request.RawUrl }, null)</li>
                            </ul>
                        </div>
                        @*<li> @Html.ActionLink(egitimsitesi.Resources.dil.Dil,"Index","Dil")</li>*@
                    </div>
                    <div class="col-sm-4">
                        @*<div class="input-group">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">Ara</button>
                                </span>
                                <input type="text" class="form-control" placeholder="Search for...">
                            </div>*@
                        @using (Html.BeginForm("Index","Home",FormMethod.Get))
                        {
                            @Html.TextBox("Arama")
                            <input type="submit" value="Ara" />
                        }
                    </div>

                </div>
                @Html.Partial("_LoginPartial")
                <br />
            </div>

        </div>
    </div>

    <div id="mySidenav" class="sidenav">
        <br />
        <br />
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>

        <span class="glyphicon glyphicon-home">@Html.ActionLink(egitimsitesi.Resources.dil.AnaSayfa, "Index", "Home")</span>
        <br />
        
        <span class="glyphicon glyphicon-eye-open">@Html.ActionLink("C++", "Cplusplus", "Kullanici")</span>
        <br />
        <span class="glyphicon glyphicon-eye-open">@Html.ActionLink("C", "C", "Kullanici")</span>
        <br />
        <span class="glyphicon glyphicon-eye-open">@Html.ActionLink("C#", "Csharp", "Kullanici")</span>
        <br />
        
        <span class="glyphicon glyphicon-eye-open">@Html.ActionLink("Java", "Java", "Kullanici")</span>
        <br />
        <span class="glyphicon glyphicon-eye-open">@Html.ActionLink(egitimsitesi.Resources.dil.Sohbet, "Chat", "Home")</span>
        <br />

        <span class="glyphicon glyphicon-envelope">@Html.ActionLink(egitimsitesi.Resources.dil.İletişim, "Contact", "Home")</span>
        <br />
        <span class="glyphicon glyphicon-envelope">@Html.ActionLink(egitimsitesi.Resources.dil.Hakkında, "About", "Home")</span>
        <br />
    </div>
    <div class="container body-content">
        <object type="application/x-shockwave-flash" width="150" height="30" data="https://www.youtube.com/v/95j3PB3ahw0?version=2&autoplay=1&loop=1&theme=dark"><param name="movie" value="https://www.youtube.com/v/95j3PB3ahw0?version=2&autoplay=1&loop=1&theme=dark" /><param name="wmode" value="transparent" /></object>
        @RenderBody()
        <hr />
        <footer>
            <div class="panel panel-default">
                <p style="margin:0;">&nbsp; &copy; @DateTime.Now.Year Eğitim Sitesi &nbsp; &nbsp; <button class="btn btn-facebook"><i class="fa fa-facebook"></i>Facebook</button> <button class="btn btn-twitter"><i class="tw tw-twitter"></i>Twitter</button></p>
            </div>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @if (ViewBag.Message != null)
    {
        <script>

            $(document).ready(function(){

            alert('@ViewBag.Message');

            });

        </script>

    }
    <script>
    var myIndex = 0;
    carousel();

    function carousel() {
        var i;
        var x = document.getElementsByClassName("mySlides");
        for (i = 0; i < x.length; i++) {
           x[i].style.display = "none";
        }
        myIndex++;
        if (myIndex > x.length) {myIndex = 1}
        x[myIndex-1].style.display = "block";
        setTimeout(carousel, 2000); // Change image every 2 seconds
    }
    </script>
</body>
</html>